// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxvrxbrssdfyzwxqpdos.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4dnJ4YnJzc2RmeXp3eHFwZG9zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEzNDIxODUsImV4cCI6MjA4NjkxODE4NX0.4jrfRN24oTFI_9HJumJgJB38Qg8SFhLJ1j_dobkaAwc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});